---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Epichouse Homelab
background: 
  image: /images/background.jpg
  blur: sm
  brightness: 10
  opacity: 40
#  saturate: 50

headerStyle: clean

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true




layout:
  Self Hosted Services:
    tab: Services
    style: column
  Third Party Services and Tools:
    tab: Services
    style: column
  Productivity Tools:
    tab: Services
    style: column
  Manchester Infrastructure:
    tab: Infrastructure
    style: column
  London Infrastructure:
    tab: Infrastructure
    style: column
#groupsInitiallyCollapsed: true
useEqualHeights: true
disableCollapse: true
theme: dark
color: neutral
#
#providers:
#  openweathermap: openweathermapapikey
#  weatherapi: weatherapiapikey

