---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Homepage
#background: 
#  image: /images/background.jpg
#  blur: sm
#  brightness: 10
#  opacity: 40
#  saturate: 50

headerStyle: clean

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true




layout:
  Self Hosted Services:
    style: column
  Third Party Services and Tools:
    style: column
  Productivity Tools:
    style: column
  Manchester Infrastructure:
    style: row
  London Infrastructure:
    style: row
#groupsInitiallyCollapsed: true
useEqualHeights: true
disableCollapse: true
theme: dark
color: neutral
#
#providers:
#  openweathermap: openweathermapapikey
#  weatherapi: weatherapiapikey

