name: Docker - Dashy Build & Deploy
on:
  workflow_dispatch:
  push:
    paths:
      - dashy/**
    paths-ignore:
      - '**/README.md'
jobs:
  development:
    permissions:
      contents: read
      packages: write
    uses: epichouse/workflow-templates/.github/workflows/docker-build.yaml@main
    with:
      docker_env: development
      docker_server: ${{ vars.testing_server}}
      docker_path: ${{ vars.docker_path}}
      docker_project: "dashy"
    secrets:
      server_username: ${{ secrets.server_username }}
  production:
    needs: development
    permissions:
      contents: read
      packages: write
    if: github.ref == 'refs/heads/main'
    uses: epichouse/workflow-templates/.github/workflows/docker-build.yaml@main
    with:
      docker_env: latest
      docker_server: ${{ vars.production_server}}
      docker_path: ${{ vars.docker_path}}
      docker_project: "dashy"
    secrets:
      server_username: ${{ secrets.server_username }}
