name: Docker Workflow
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/README.md'
jobs:
  development:
    if: github.ref == 'refs/heads/dev'
    uses: epichouse/workflowtemplates/.github/workflows/docker-build.yaml@main
    with:
      docker_env: development
      docker_server: ${{ vars.testing_server}}
      docker_image: ${{ vars.docker_image}}
      docker_path: ${{ vars.docker_path}}
    secrets:
      dockerhub_token: ${{ secrets.dockerhub_token }}
      dockerhub_username: ${{ secrets.dockerhub_username }}
      server_username: ${{ secrets.server_username }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  production:
    if: github.ref == 'refs/heads/main'
    uses: epichouse/workflowtemplates/.github/workflows/docker-build.yaml@main
    with:
      docker_env: latest
      docker_server: ${{ vars.production_server}}
      docker_image: ${{ vars.docker_image}}
      docker_path: ${{ vars.docker_path}}
    secrets:
      dockerhub_token: ${{ secrets.dockerhub_token }}
      dockerhub_username: ${{ secrets.dockerhub_username }}
      server_username: ${{ secrets.server_username }}
